version: '3.8'

services:
  backend:
    build: 
      context: ./smth_backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/valentines
      SPRING_DATASOURCE_USERNAME: andrejadajkin
      SPRING_DATASOURCE_PASSWORD: 12345678
    depends_on:
      - db
    networks:
      - dev1

  frontend:
    build: 
      context: ./valentines_front
    ports:
      - "3000:3000"
    networks:
      - dev1

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: smth_database
      MYSQL_USER: andrejadajkin
      MYSQL_PASSWORD: 12345678
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3307"
    networks:
      - dev1

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "81:81"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - dev1

volumes:
  db_data:
    driver: local

networks:
  dev:
    driver: bridge